services:
  - type: web
    name: erp-testing-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
      - key: NODE_VERSION
        value: 20
